[features]
seeds = false
skip-lint = false
[programs.localnet]
zipline = "8KKAek3c9jAT9PPFTfwbpQwrd4av8WH5qKSc8BgfCD1R"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/arowana/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
